#!/bin/sh
# Fetch the XISF 1.0 specification and convert it to Markdown for local reference.
#
# The specification is authored in PIDoc and compiled to HTML. PIDoc source for it
# does exist publicly, at github.com/GeorgViehoever/XISF-specification — but that
# copy last changed in 2016 and titles itself "DRAFT 6->7", while the published
# document is generated 2022-03-12. Drafts 3 through 8 sit between them, and this
# design cites the specification by section number, so a stale source would point
# every citation somewhere subtly wrong. There is no PixInsight GitHub organisation
# to pull an authoritative copy from. The compiled HTML is therefore the authority.
#
# Output is gitignored: it is Pleiades Astrophoto's documentation, format-shifted,
# and this repository does not redistribute it.

set -eu

URL="https://pixinsight.com/doc/docs/XISF-1.0-spec/XISF-1.0-spec.html"
DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
HTML="$DIR/reference/xisf-1.0-spec.html"
MD="$DIR/reference/xisf-1.0-spec.md"

mkdir -p "$DIR/reference"

# The server answers 406 to curl's default headers, so send ones it accepts.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

echo "fetching $URL"
curl -fsSL --retry 3 --retry-delay 2 \
     -H "User-Agent: $UA" \
     -H "Accept: text/html,application/xhtml+xml" \
     -o "$HTML" "$URL"

# The compiler stamps a generation date into the footer. Record it: it is the only
# version marker the document carries, and it is what distinguishes this from the
# drafts that share its title.
STAMP=$(grep -o 'Generated by the PixInsight Documentation Compiler[^<]*' "$HTML" | head -1 || true)
[ -n "$STAMP" ] && echo "  $STAMP"

echo "converting"
python3 "$DIR/tools/xisf-spec-to-md.py" "$HTML" -o "$MD"

echo
echo "  html : $HTML"
echo "  md   : $MD"
[ -n "$STAMP" ] && echo "  stamp: $STAMP"
echo
echo "Both are gitignored. Cite by section number; do not quote at length."
