#!/bin/sh
# Fetch the XISF specification and convert it to Markdown for local reference.
#
# The specification is authored in PIDoc and compiled to HTML. Both are published: the PIDoc
# source lives at gitlab.com/pixinsight/XISF-specification, which the specification's own §4
# names. The compiled HTML is nonetheless the authority here, for a mechanical reason rather
# than a judgement about trust — section, table and equation numbers are assigned by the
# documentation compiler at build time, so no `.pidoc` file can tell you that a subsection is
# §8.3.5. A repository that cites by number has to read the rendered document.
#
# `gitlab.com/pixinsight/PCL`, which §4 now advertises directly beside the specification
# repository, is the C++ reference implementation and is NOT to be consulted: this crate is
# written from the specifications alone, which is what keeps it permissively licensable.
#
# The document has moved under this fixed URL before — Revision 1 replaced the April 2017 text
# at the same path with the same filename — so the compiler stamp is compared against the build
# reference/README.md records, and a mismatch is reported loudly. Section, table and equation
# numbers have all moved across a revision before.
#
# Output is gitignored: it is Pleiades Astrophoto's documentation, format-shifted, and this
# repository does not redistribute it.

set -eu

URL="https://pixinsight.com/doc/docs/XISF-1.0-spec/XISF-1.0-spec.html"
DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
HTML="$DIR/reference/xisf-1.0-spec.html"
MD="$DIR/reference/xisf-1.0-spec.md"
STAMP_FILE="$DIR/reference/xisf-1.0-spec.stamp"
README="$DIR/reference/README.md"

mkdir -p "$DIR/reference"

# The server answers 406 to curl's default headers, so send ones it accepts.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

echo "fetching $URL"
curl -fsSL --retry 3 --retry-delay 2 \
     -H "User-Agent: $UA" \
     -H "Accept: text/html,application/xhtml+xml" \
     -o "$HTML" "$URL"

# The compiler stamps a generation date into the footer. It is the only version marker the
# document carries: the filename cannot express it, the format version stays 1.0 across a
# document revision, and the URL does not change.
STAMP=$(grep -o 'Generated by the PixInsight Documentation Compiler[^<]*' "$HTML" | head -1 || true)
if [ -n "$STAMP" ]; then
    echo "  $STAMP"
    printf '%s\n' "$STAMP" > "$STAMP_FILE"
fi

echo "converting"
python3 "$DIR/tools/xisf-spec-to-md.py" "$HTML" -o "$MD"

echo
echo "  html : $HTML"
echo "  md   : $MD"
[ -n "$STAMP" ] && echo "  stamp: $STAMP"
echo

EXPECTED=$(sed -n 's/^Verified against: //p' "$README" | head -1)
if [ -n "$EXPECTED" ] && [ -n "$STAMP" ] && [ "$STAMP" != "$EXPECTED" ]; then
    echo "WARNING: this is not the build this repository's citations were checked against."
    echo "  expected: $EXPECTED"
    echo "  fetched : $STAMP"
    echo
    echo "Section, table and equation numbers have moved across a revision before. Re-check the"
    echo "citations before relying on one, then update the 'Verified against:' line in"
    echo "reference/README.md in the same change."
    echo
fi

echo "Both are gitignored. Cite by section number; do not quote at length."
